logging:
  level.: ERROR
  level.no.brreg: INFO
  level.no.difi: ERROR
  level.no.dcat: INFO
  level.org.springframework: ERROR
server:
  port: 8080
management:
  port: 8181
health:
  config:
    enabled: false
spring:
  hateoas:
    use-hal-as-default-json-media-type: false
---

spring:
  profiles: develop
server:
  port: 8098
management:
  port: 8998

---

spring:
  profiles: unit-integration
