spring:
    profiles: docker
application:
  elasticsearchHost: elasticsearch
  elasticsearchPort: 9300
---
spring:
    profiles: development
application:
  elasticsearchHost: localhost
  elasticsearchPort: 9300
