
#Denne filen brukes når applikasjonen kjører på utvikler pc.
logging:
  level.: ERROR
  level.no.brreg: DEBUG
  level.org.springframework: ERROR

#Kanskje kan disse fjernes?
spring:
    profiles: docker
application:
  elasticsearchHost: elasticsearch
  elasticsearchPort: 9300
---
spring:
    profiles: development
application:
  elasticsearchHost: localhost
  elasticsearchPort: 9300
