spring:
    profiles: docker
logging:
  level.: ERROR
  level.no.brreg: DEBUG
  level.org.springframework: ERROR
application:
  elasticsearchHost: elasticsearch
  elasticsearchPort: 9300
  clusterName: elasticsearch
---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop
logging:
  level.: ERROR
  level.no.brreg: DEBUG
  level.org.springframework: ERROR
application:
  elasticsearchHost: localhost
  elasticsearchPort: 9300
  clusterName: elasticsearch
server:
  port: 8083
management:
  port: 8993

