spring:
  jackson:
    default-property-inclusion: non_null
  data:
    elasticsearch:
      clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch5:9300}
      clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}

logging:
  level.root: WARN
  level.no.ccat: ${LOG_LEVEL:INFO}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.springframework.data.elasticsearch: ${LOG_LEVEL:INFO}
application:
  apiRootUrl: http://nginx-search:8080/api
  apiRootExternalURL: https://fellesdatakatalog.brreg.no/api
  conceptsPath: /concepts
  harvestSourceUri: https://data.brreg.no/begrep/


---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop, unit-integration
  data:
    elasticsearch:
      clusterNodes: localhost:9300
      clusterName: elasticsearch
application:
  apiRootUrl: http://localhost:8080/api
  apiRootExternalURL: http://localhost:8080/api
  conceptsPath: /concepts
server:
  port: 8088
