matrix:
  include:
    - language: java
      jdk:
        - oraclejdk8
    - language: node_js
      node_js:
      - "lts/8"

services:
  - docker # enable docker support in travis

apt:
  sources:
    - google-chrome # we need to install chrome for running the Angular e2e tests
  packages:
    - google-chrome-stable

before_install:
#  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - # we need nodejs for building the Angular code
#  - sudo apt-get install -y  > /dev/null
#  - sudo apt-get install -y build-essential > /dev/null
install:
  - export DOCKER_HOST=unix:///var/run/docker.sock # required by the docker maven plugin for connecting to docker
  - export CHROME_BIN=chromium-browser # this line and the next two lines are required for running up chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  except:
    - /ut1_.*/
    - /st1_.*/
    - /st2_.*/
    - /tt1_.*/
    - /ppe_.*/
jobs:
  include:
    - stage: Build # First build the project to look for syntax/build problems
      script: travis_wait mvn install -DskipTests -Dmaven.javadoc.skip=true
      env:
        - comment=First build the project to look for syntax/build problems

    - stage: Tests # Run regular unit tests
      script: mvn install -DskipTests -DskipDockerBuild -Dmaven.javadoc.skip=true -Dmaven.exec.skip=true -B > /dev/null && mvn test -B
      env:
        - comment=Run regular unit tests

#    - stage: Tests # Run unit and intergation tests + generate test coverage report
#      script: mvn install -DskipTests -Dmaven.javadoc.skip=true -B && docker-compose up -d  && ./waitForDocker.sh  &&  mvn verify -DskipDockerBuild -B -P all-tests org.jacoco:jacoco-maven-plugin:report
#      after_success:
#        - mvn org.eluder.coveralls:coveralls-maven-plugin:report
#      env:
#        - comment=Run unit and intergation tests + generate test coverage report

#    - stage: Tests # Run Angular e2e tests
#      script: mvn install -DskipTests -Dmaven.javadoc.skip=true -B && docker-compose up -d  && ./waitForDocker.sh &&  ./runNodeTests.sh
#      env:
#        - comment=Run Angular e2e tests

#    - stage: deploy
#      script: mvn install -DskipTests -Dmaven.javadoc.skip=true -B ;
#      deploy:
#        provider: script
#        skip_cleanup: true
#        script:
#          - ./travisPushToDockerHub.sh
#        on:
##          branch: develop
#          condition: $TRAVIS_TAG = ''
