language: java
services:
  - docker
jdk:
  - oraclejdk8
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install -y nodejs | /dev/null
  - sudo apt-get install -y build-essential | /dev/null
install:
  - export DOCKER_HOST=unix:///var/run/docker.sock
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mvn install -DskipTests -Dmaven.javadoc.skip=true -Dskip.npm -B -T 1C
  - cd docker ; docker-compose up -d ; ./waitForDocker.sh ; cd ..
script:
#  - mvn test -B  org.jacoco:jacoco-maven-plugin:report
  - mvn test -B  org.jacoco:jacoco-maven-plugin:report && mvn -B  failsafe:integration-test org.jacoco:jacoco-maven-plugin:report  && ./runNodeTests.sh
after_success:
  - mvn org.eluder.coveralls:coveralls-maven-plugin:report