language: java
services:
  - docker
jdk:
  - oraclejdk8
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install -y nodejs > /dev/null
  - sudo apt-get install -y build-essential > /dev/null
install:
  - export DOCKER_HOST=unix:///var/run/docker.sock
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


jobs:
  include:
    - stage: Build
      script: mvn install -DskipTests -DskipDockerBuild -Dmaven.javadoc.skip=true -Dskip.npm -B
    - stage: Tests
      script:   mvn install -DskipTests -Dmaven.javadoc.skip=true -Dskip.npm -B -T 2C -q > /dev/null && mvn test -B
    - stage: Tests
      script:   mvn install -DskipTests -Dmaven.javadoc.skip=true -Dskip.npm -B -T 2C -q > /dev/null && cd docker  && docker-compose up -d  && ./waitForDocker.sh  && cd .. && mvn verify -B -P all-tests org.jacoco:jacoco-maven-plugin:report
      after_success:
        - mvn org.eluder.coveralls:coveralls-maven-plugin:report
    - stage: Tests
      script: mvn install -DskipTests -Dmaven.javadoc.skip=true -Dskip.npm -B -T 2C -q > /dev/null && cd docker ; docker-compose up -d ; ./waitForDocker.sh ; cd ..; ./runNodeTests.sh

