version: "3"

services:
### external modules
  elasticsearch5:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    expose:
      - "9200"
      - "9300"

  fuseki:
    image: dcatno/fuseki:latest
    volumes:
      - fuseki-data:/etc/fuseki/databases/
    expose:
      - "8080"

  sso:
    image: jboss/keycloak
    expose:
      - "8080"

### ingress modules
  nginx-search:
    image: dcatno/nginx-search:latest
    expose:
      - "8080"
    depends_on:
      - search
      - search-api
      - harvester-api
      - api-cat
      - concept-cat
      - informationmodel-cat

  nginx-registration:
    image: dcatno/nginx-registration:latest
    expose:
      - "8080"
    depends_on:
      - registration-react
      - registration-api
      - reference-data

### nodejs modules
  search:
    image: dcatno/search:latest
    expose:
      - "3000"

  registration-react:
    image: dcatno/registration-react:latest
    expose:
      - "4300"

### java modules
  api-cat:
    image: dcatno/api-cat:latest
    expose:
      - "8080"
    depends_on:
      - elasticsearch5
      - reference-data
      - search-api

  concept-cat:
    image: dcatno/concept-cat:latest
    expose:
      - "8080"

  informationmodel-cat:
    image: dcatno/informationmodel-cat:latest
    expose:
      - "8080"

  harvester:
    image: dcatno/harvester:latest
    expose:
      - "8080"
    depends_on:
      - fuseki
      - harvester-api

  harvester-api:
    image: dcatno/harvester-api:latest
    expose:
      - "8080"
    depends_on:
      - fuseki
      - elasticsearch5
      - reference-data

  registration-api:
    image: dcatno/registration-api:latest
    expose:
      - "8080"
    depends_on:
      - elasticsearch5
      - reference-data
      - registration-auth
      - api-cat

  reference-data:
    image: dcatno/reference-data:latest
    expose:
      - "8080"

  search-api:
    image: dcatno/search-api:latest
    expose:
      - "8080"
    depends_on:
      - elasticsearch5

  user-api:
    image: dcatno/user-api:latest
    expose:
      - "8080"

### test and mock modules
  registration-auth:
    image: dcatno/registration-auth:latest
    expose:
      - "8080"

  e2e:
    image: dcatno/e2e:latest
    volumes:
      - ./applications/e2e/test:/usr/src/app/test:rw

volumes:
  fuseki-data:
  elasticsearch-data:
