version: "3"

services:
  search:
    image: dcatno/search:latest

  search-api:
    image: dcatno/search-api:latest
    depends_on:
      - elasticsearch

  nginx-search:
    image: dcatno/nginx-search:latest
    depends_on:
      - search
      - search-api
      - harvester-api

  fuseki:
    image: dcatno/fuseki:latest

  harvester-api:
    image: dcatno/harvester-api:latest
    depends_on:
     - fuseki
     - elasticsearch
     - reference-data

  harvester:
    image: dcatno/harvester:latest
    depends_on:
     - elasticsearch
     - fuseki
     - harvester-api

  elasticsearch:
    image: elasticsearch:2.4.1

  dev-management:
    image: dcatno/dev-management:latest
    depends_on:
      - elasticsearch
      - fuseki
      - harvester-api

  nginx-registration:
      image: dcatno/nginx-registration:latest
      depends_on:
        - registration-api
        - reference-data

  registration-api:
    image: dcatno/registration-api:latest
    depends_on:
      - elasticsearch
      - reference-data
      - registration-auth

  registration-react:
    image: dcatno/registration-react:latest
    build: ./applications/registration-react
    depends_on:
      - nginx-registration-ssl
      - registration-api

  reference-data:
    image: dcatno/reference-data:latest

  registration-auth:
    image: dcatno/registration-auth:latest

  registration-validator:
    image: dcatno/registration-validator:latest
