logging:
  level.: ERROR
  level.no.brreg: DEBUG
  level.org.springframework: ERROR
---
spring:
    profiles: docker
application:
  elasticsearchHost: elasticsearch
  elasticsearchPort: 9300
  clusterName: elasticsearch
---
#Utv-miljø lokalt på egen PC
spring:
    profiles: development
application:
  elasticsearchHost: 192.168.99.100
  elasticsearchPort: 9300
  clusterName: elasticsearch
