data:
  elasticsearch:
    clusterNodes: localhost:9300
    clusterName: elasticsearch
application:
  catalogUriPrefix: http://localhost:8099
  themesServiceUrl: http://localhost:8100
  apikey: ${reg_apikey:12345-ABCDE-67890-FGHIJ}
  altinnServiceUrl: ${reg_altinnServiceUrl:http://localhost:8077}
  altinnServiceCode: ${reg_altinnServiceCode:4814}
  altinnServiceEdition: ${reg_altinnServiceEdition:3}
  clientSSLCertificateKeystoreLocation: ${reg_clientSSLCertificateKeystoreLocation:../conf/dummy-client-SSL-cert.p12}
  clientSSLCertificateKeystorePassword: ${reg_clientSSLCertificateKeystorePassword:password}
spring:
  hateoas:
    use-hal-as-default-json-media-type: false

---
spring:
  profiles: prod
application:
  altinnServiceUrl: http://localhost:8077
server:
  tomcat:
    accesslog:
      enabled: true
    basedir: /tmp/fdk
  ssl:
    key-store: ${reg_sslKeystoreLocation:conf/idporten/ssldevelop.p12}
    key-store-password: ${reg_sslKeyPassword:changeit}
    key-store-type: PKCS12
    key-alias: tomcat
saml:
  sso:
    default-success-url: /index.html
    metadata-generator:
      entity-id: difi.brreg.datakatalog.registrering.dev
    logout:
      default-target-url: /loggetut
      single-logout-url: registrering/saml/SingleLogout
    idp:
      metadata-location: file:conf/idporten/idporten-ver2.difi.no-v3_signed_meta.xml
    metadata-manager:
      refresh-check-interval: -1
    key-manager:
      public-key-pem-location: file:conf/idporten/difi.brreg.datakatalog.registrering.dev.xml
      store-location: file:conf/idporten/difi.brreg.datakatalog.registrering.dev.jks
      store-pass: ${reg_ipStorePassword}
      default-key: difi.brreg.datakatalog.registrering.dev
      key-passwords:
        difi.brreg.datakatalog.registrering.dev: ${reg_ipKeyPassword}
    sso-processing-url: registrering/saml/SSO

---
spring:
  profiles: develop
server:
  port: 8099
  ssl:
    key-store: ${reg_sslKeystorePassword:conf/idporten/ssldevelop.p12}
    key-store-password: ${reg_sslKeyPassword:changeit}
    key-store-type: PKCS12
    key-alias: tomcat


---
spring:
  profiles: unit-integration
  data:
    elasticsearch:
      clusterNodes: localhost:9300
      clusterName: elasticsearch
      properties:
        http:
          enabled: true
application:
  clientSSLCertificateKeystoreLocation: ../conf/dummy-client-SSL-cert.p12
  clientSSLCertificateKeystorePassword: password
---
spring:
  profiles: develop_embedded
  data:
    elasticsearch:
      properties:
        http:
          enabled: true
server:
  port: 8099
  tomcat:
    accesslog:
      enabled: true
    basedir: /tmp/fdk
management:
  port: 8999


---
spring:
  profiles: docker
server:
  ssl:
    key-store: ${reg_sslKeystorePassword:conf/idporten/ssldevelop.p12}
    key-store-password: ${reg_sslKeyPassword:changeit}
    key-store-type: PKCS12
    key-alias: tomcat


