spring:
  profiles: develop
  data:
    elasticsearch:
      clusterNodes: localhost:9300
  application:
      catalogUriPrefix: http://localhost:8099
      themesServiceUrl: http://localhost:8100
server:
  port: 8099
management:
  port: 8999
---
spring:
  profiles: unit-integration
  data:
    elasticsearch:
      clusterNodes: localhost:9300
      clusterName: elasticsearch
      properties:
        http:
          enabled: true
  application:
      catalogUriPrefix: http://localhost:8099
      themesServiceUrl: http://localhost:8100
---
spring:
  profiles: develop_embedded
  data:
    elasticsearch:
      properties:
        http:
          enabled: true
  application:
    catalogUriPrefix: http://localhost:8099
server:
  port: 8099
  tomcat:
    accesslog:
      enabled: true
    basedir: /tmp/fdk
management:
  port: 8999


---
spring:
  profiles: docker
  data:
    elasticsearch:
      clusterNodes: elasticsearch:9300
  application:
    catalogUriPrefix: http://localhost:8099
---
spring:
  hateoas:
    use-hal-as-default-json-media-type: false