spring:
  profiles: develop
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
server:
  port: 8099
management:
  port: 8999
---

spring:
  profiles: unit-integration
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
server:
  port: 8099
management:
  port: 8999
