spring:
  profiles: docker
application:
  queryService: http://search-api:8080
  queryServiceExternal: http://localhost:8083
  fusekiService: http://fuseki:8080/fuseki
  themeServiceExternalUrl: http://localhost:8100
  themeServiceUrl: http://reference-data:8080
---
spring:
  profiles: test
application:
  queryService: http://localhost:8071
  queryServiceExternal: http://localhost:8071
  fusekiService: http://localhost:3030/fuseki
  themeServiceExternalUrl: http://localhost:8100
  themeServiceUrl: http://reference-data:8080

---
spring:
  profiles: develop
application:
  queryService: http://localhost:8083
  queryServiceExternal: http://localhost:8083
  fusekiService: http://localhost:3030/fuseki
  themeServiceExternalUrl: http://localhost:8100
  themeServiceUrl: http://reference-data:8080
server:
  port: 8080
management:
  port: 9090