logging:
  level.: ERROR
  level.no.brreg: DEBUG
  level.no.difi: ERROR
  level.no.dcat: DEBUG
  level.org.springframework: ERROR
server:
  port: 8080
management:
  port: 8181
application:
  queryService: http://search-api:8080
  queryServiceExternal: ${search_queryServiceExternal:http://localhost:8083}
  fusekiService: http://fuseki:8080/fuseki
  themeServiceExternalUrl: ${search_referenceDataExternalUrl:http://localhost:8100}
  themeServiceUrl: http://reference-data:8080

---

spring:
  profiles: docker
application:
  queryServiceExternal: http://localhost:8083
  themeServiceExternalUrl: http://localhost:8100
---
spring:
  profiles: test
application:
  queryService: http://localhost:8071
  queryServiceExternal: http://localhost:8071
  fusekiService: http://localhost:3030/fuseki
  themeServiceExternalUrl: http://localhost:8100
  themeServiceUrl: http://reference-data:8080

---
spring:
  profiles: develop
application:
  queryService: http://localhost:8083
  queryServiceExternal: http://localhost:8083
  fusekiService: http://localhost:3030/fuseki
  themeServiceExternalUrl: http://localhost:8100
  themeServiceUrl: http://reference-data:8080
server:
  port: 8080
management:
  port: 9090