version: "2"

services:
  search:
    image: dcatno/search:latest
    links:
      - search-api
    networks:
      platform:

  search-api:
    image: dcatno/search-api:latest
    links:
      - elasticsearch
    networks:
      platform:

  gdoc:
    image: dcatno/gdoc:latest
    networks:
      platform:

  validator:
    image: dcatno/validator:latest
    networks:
      platform:

  fuseki:
    image: dcatno/fuseki:latest
    networks:
      platform:

  harvester:
    image: dcatno/harvester:latest
    networks:
      platform:
      logging:
    links:
     - fuseki
     - elasticsearch
     - gdoc
     - registrering

  admin:
    image: dcatno/admin-webapp:latest
    networks:
      platform:
      logging:
    depends_on:
     - elasticsearch
    links:
     - fuseki
     - harvester

 # elasticsearch5:
 #   image: "docker.elastic.co/elasticsearch/elasticsearch:5.2.0"
 #   environment:
 #     - xpack.security.enabled=false
 #     - cluster.name=elasticsearch
 #   ports:
 #     - "920:9200"
 #     - "9300:9300"
 #   networks:
 #     platform:
 #       aliases:
 #         - es
 #     logging:
 #       aliases:
 #         - log_es

  elasticsearch:
    image: dcatno/elasticsearch:latest
    networks:
      platform:
      logging:

  test:
    image: dcatno/test:latest
    links:
      - elasticsearch
      - fuseki
      - harvester
    networks:
      platform:

  registrering:
    image: dcatno/reg-api:latest
    links:
      - elasticsearch
    networks:
      platform:

  reg-gui:
    image: dcatno/reg-gui:latest
    links:
      - elasticsearch
    networks:
      platform:

#  logstash:
#    image: "dcatno/logstash:${TAG}"
#    entrypoint: /opt/logstash/bin/logstash -f /etc/logstash/conf.d/logstash.conf
#    volumes:
#      - ./logs:/usr/local/tomcat/logs:rw
#    depends_on:
#      - elasticsearch
#    networks:
#      logging:

#  kibana:
#    image: dcatno/kibana:latest
#    depends_on:
#      - elasticsearch
#    networks:
#      logging:

networks:
  platform:
  logging:
