version: "2"

services:
  search:
    image: dcatno/search:latest
    environment:
         - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Xmx512M
    links:
      - search-api
      - fuseki
    networks:
      platform:

  search-api:
    image: dcatno/search-api:latest
    environment:
         - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Xmx512M
    links:
      - elasticsearch
    networks:
      platform:

  gdoc:
    image: dcatno/gdoc:latest
    environment:
         - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Xmx512M
    networks:
      platform:

  fuseki:
    image: dcatno/fuseki:latest
    networks:
      platform:

  harvester-api:
    image: dcatno/harvester-api:latest
    environment:
         - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Xmx512M
    networks:
      platform:
      logging:
    links:
     - fuseki
     - elasticsearch

  harvester:
    image: dcatno/harvester:latest
    environment:
         - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Xmx512M
    networks:
      platform:
      logging:
    depends_on:
     - elasticsearch
    links:
     - fuseki
     - harvester-api

 # elasticsearch5:
 #   image: "docker.elastic.co/elasticsearch/elasticsearch:5.2.0"
 #   environment:
 #     - xpack.security.enabled=false
 #     - cluster.name=elasticsearch
 #   ports:
 #     - "920:9200"
 #     - "9300:9300"
 #   networks:
 #     platform:
 #       aliases:
 #         - es
 #     logging:
 #       aliases:
 #         - log_es

  elasticsearch:
    image: elasticsearch:2.4.1
    networks:
      platform:
      logging:

  test:
    image: dcatno/test:latest
    environment:
         - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Xmx512M
    links:
      - elasticsearch
      - fuseki
      - harvester-api
    networks:
      platform:

  registration-api:
    image: dcatno/registration-api:latest
    environment:
         - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Xmx512M
    links:
      - elasticsearch
      - search-api
    networks:
      platform:

  registration:
    image: dcatno/registration:latest
    environment:
         - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Xmx512M
    links:
      - registration-api
      - validator
    networks:
      platform:

  validator:
    image: dcatno/validator:latest
    environment:
         - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Xmx512M
    networks:
      platform:


# logstash:
#   image: dcatno/logstash:latest
#   entrypoint: /opt/logstash/bin/logstash -f /etc/logstash/conf.d/logstash.conf
#    volumes:
#      - ./logs:/usr/local/tomcat/logs:rw
#    depends_on:
#      - elasticsearch
#    networks:
#      logging:

#  kibana:
#    image: kibana:2.4.1
#    depends_on:
#      - elasticsearch
#    networks:
#      logging:

networks:
  platform:
  logging:
