version: "2"

services:
  fuseki:
    image: "fdk/fuseki:${TAG}"
    ports:
     - "3030:8080"
    networks:
      platform:

  harvester:
    image: "fdk/harvester-app:${TAG}"
    ports:
     - "8081:8080"
    environment:
     - JAVA_OPTS="-Dspring.profiles.active=docker"
     - fuseki.dcatServiceUri=http://fuseki:8080/fuseki/dcat
     - fuseki.adminServiceUri=http://fuseki:8080/fuseki/admin
     - application.elasticSearchHost=http://elasticsearch:9300
    volumes:
     - ./logs:/usr/local/tomcat/logs:rw
    networks:
      platform:
      logging:
    depends_on:
     - fuseki
     - elasticsearch
    links:
     - fuseki
     - elasticsearch

  admin-webapp:
    image: "fdk/admin-webapp:${TAG}"
    ports:
     - "8082:8080"
    environment:
     - JAVA_OPTS="-Dspring.profiles.active=docker"
     - fuseki.dcatServiceUri=http://fuseki:8080/fuseki/dcat
     - fuseki.adminServiceUri=http://fuseki:8080/fuseki/admin
     - application.harvesterUrl=http://harvester:8080
     - application.kibanaLinkFirstHalf="/app/kibana/#/dashboard/dashboard_template?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(filters:!(),options:(darkTheme:!f),panels:!((col:4,id:Crawler-Operations,panelIndex:1,row:3,size_x:9,size_y:3,type:visualization),(col:1,id:Crawler-Results,panelIndex:2,row:3,size_x:3,size_y:3,type:visualization),(col:1,id:Crawler-Metadata,panelIndex:4,row:1,size_x:12,size_y:2,type:visualization),(col:7,id:Validation-RuleId,panelIndex:6,row:6,size_x:6,size_y:4,type:visualization),(col:1,columns:!(ruleSeverity,event,cause,ruleId),id:validation_ruleId,panelIndex:7,row:6,size_x:6,size_y:4,sort:!(timestamp,desc),type:search)),query:(query_string:(analyze_wildcard:!t,query:'%22"
     - application.kibanaLinkSecondHalf="%22')),title:dashboard_template,uiState:())"
    volumes:
     - ./logs:/usr/local/tomcat/logs:rw
    networks:
      platform:
      logging:
    depends_on:
     - elasticsearch
    links:
     - fuseki
     - harvester

  elasticsearch:
    image: "fdk/elasticsearch:${TAG}"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      platform:
      logging:

  logstash:
    image: "fdk/logstash:${TAG}"
    entrypoint: /opt/logstash/bin/logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logs:/usr/local/tomcat/logs:rw
    depends_on:
      - elasticsearch
    networks:
      logging:

  kibana:
    image: "fdk/kibana:${TAG}"
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      logging:

networks:
  platform:
  logging:
