logging:
  level.: ERROR
  level.no.brreg: ERROR
  level.no.difi: INFO
  level.no.dcat: INFO
  level.org.springframework: ERROR
  level.org.springframework.web: ERROR
  level.org.elasticsearch: WARN
server:
  port: 8080
management:
  port: 8181
application:
  httpUsername: ${themesHttpUsername:user}
  httpPassword: ${themesHttpPassword:password}
  crawlerThreadPoolSize: 2
  elasticSearchHost: elasticsearch
  elasticSearchPort: 9300
  elasticSearchCluster: elasticsearch
  themesHostname: http://reference-data:8080
fuseki:
  dcatServiceUri: http://fuseki:8080/fuseki/dcat
  adminServiceUri: http://fuseki:8080/fuseki/admin

---
spring:
  profiles: docker
  mail:
    host: smtp.gmail.com
    port: 587
    username: fdksystembjg
    password: xxxx
    properties:
      mail:
        smtp:
          auth: true
          connectionTimeout: 5000
          timeout: 3000
          writetimeout: 5000
          starttls:
            enable: true

---
spring:
  profiles: prod
  mail:
    host: smtprelay@brreg.no
    port: 587
    username: ${emailUsername}
    password: ${emailPassword}
    properties:
      mail:
        smtp:
          auth: true
          connectionTimeout: 5000
          timeout: 3000
          writetimeout: 5000
          starttls:
            enable: true
application:
  elasticSearchCluster: fellesdatakatalog
  notificationMailSenderAddress: ${emailSenderAddress}

---
spring:
  profiles: develop, unit-integration
  mail:
    host: smtp.gmail.com
    port: 587
    username: fdksystembjg
    password: xxxx
    properties:
      mail:
        smtp:
          auth: true
          connectionTimeout: 5000
          timeout: 3000
          writetimeout: 5000
          starttls:
            enable: true
logging:
  level.: ERROR
  level.no.brreg: ERROR
  level.no.difi: INFO
  level.no.dcat: INFO
  level.org.springframework: ERROR
  level.org.springframework.web: ERROR
fuseki:
  dcatServiceUri: http://localhost:3030/fuseki/dcat
  adminServiceUri: http://localhost:3030/fuseki/admin
application:
  crawlerThreadPoolSize: 2
  elasticSearchHost: localhost
  elasticSearchPort: 9300
  elasticSearchCluster: elasticsearch
  themesHostname: http://localhost:8100
  notificationMailSenderAddress: fdksystembjg@gmail.com
server:
  port: 8081
management:
  port: 8991