spring:
  profiles: docker
  mvc.view.prefix: /WEB-INF/jsp/
  mvc.view.suffix: .jsp
fuseki:
  dcatServiceUri: http://fuseki:3030/dcat
  adminServiceUri: http://fuseki:3030/admin
---

spring:
  profiles: develop
  mvc.view.prefix: /WEB-INF/jsp/
  mvc.view.suffix: .jsp
fuseki:
  dcatServiceUri: http://localhost:3030/dcat
  adminServiceUri: http://localhost:3030/admin
application:
  harvesterUrl: http://localhost:8090
server:
  port: 8085
management:
  port: 8995