spring:
  profiles: docker
  mvc.view.prefix: /WEB-INF/jsp/
  mvc.view.suffix: .jsp
fuseki:
  dcatServiceUri: http://fuseki:8080/fuseki/dcat
  adminServiceUri: http://fuseki:8080/fuseki/admin
---

spring:
  profiles: development
  mvc.view.prefix: /WEB-INF/jsp/
  mvc.view.suffix: .jsp
fuseki:
  dcatServiceUri: http://localhost:3030/fuseki/dcat
  adminServiceUri: http://localhost:3030/fuseki/admin
application:
  harvesterUrl: http://localhost:8090
server:
  port: 8085
management:
  port: 8995