spring:
  profiles: docker
application:
  retrieveDatasetServiceUrl: http://localhost:8081/detail
  queryServiceUrl: http://localhost:8081/search
  retrieveDatathemesServiceURL: http://localhost:8081/themes
---
spring:
  profiles: test
application:
  retrieveDatasetServiceUrl: http://localhost:8071/detail
  queryServiceUrl: http://localhost:8071/search
  retrieveDatathemesServiceURL: http://localhost:8071/themes
---
spring:
  profiles: development
application:
  retrieveDatasetServiceUrl: http://localhost:8091/detail
  queryServiceUrl: http://localhost:8091/search
  retrieveDatathemesServiceURL: http://localhost:8091/themes
