spring:
  profiles: docker
application:
  queryService: http://query:8080
  queryServiceExternal: http://localhost:8081
---
spring:
  profiles: test
application:
  queryService: http://localhost:8071
  queryServiceExternal: http://localhost:8071
---
spring:
  profiles: develop
application:
  queryService: http://localhost:8083
  queryServiceExternal: http://localhost:8083
server:
  port: 8080
