spring:
  profiles: docker
application:
  retrieveDatasetServiceUrl: http://localhost:8080/detail
  queryServiceUrl: http://localhost:8081/search
---
spring:
  profiles: test
application:
  retrieveDatasetServiceUrl: http://localhost:8070/detail
  queryServiceUrl: http://localhost:8071/search
---
spring:
  profiles: development
application:
  retrieveDatasetServiceUrl: http://localhost:8090/detail
  queryServiceUrl: http://localhost:8091/search
