logging:
  level.root: INFO
  level.no: ${LOG_LEVEL:DEBUG}
application:
  fusekiService: http://fuseki:8080/fuseki
elastic:
  clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch5:9300}
  clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}

---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop, unit-integration
application:
  fusekiService: http://localhost:3030/fuseki
elastic:
  clusterNodes: localhost:9300
  clusterName: elasticsearch
server:
  port: 8119
