logging:
  level.: ERROR
  level.no.difi: ERROR
  level.no.dcat: DEBUG
  level.org.springframework: WARN
  level.org.springframework.web: WARN
application:
  elasticsearchHost: elasticsearch
  elasticsearchPort: 9300
  clusterName: elasticsearch
server:
  port: 8080
management:
  port: 8181

---
spring:
  profiles: prod
application:
  clusterName: fellesdatakatalog

---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop
logging:
  level.: ERROR
  level.no.brreg: DEBUG
  level.org.springframework: ERROR
server:
  port: 8083
management:
  port: 8993

