fuseki:
  dcatServiceUri: http://localhost:3030/fuseki/dcat
  adminServiceUri: http://localhost:3030/fuseki/admin
application:
  crawlerThreadPoolSize: 2
  elasticSearchHost: localhost
  elasticSearchPort: 9300
  elasticSearchCluster: elasticsearch
---
spring:
    profiles: docker
fuseki:
  dcatServiceUri: http://fuseki:3030/fuseki/dcat
  adminServiceUri: http://fuseki:3030/fuseki/admin
application:
  elasticSearchHost: es
  elasticSearchPort: 9300
  elasticSearchCluster: elasticsearch
---
spring:
    profiles: development
fuseki:
  dcatServiceUri: http://localhost:3030/fuseki/dcat
  adminServiceUri: http://localhost:3030/fuseki/admin
application:
  elasticSearchHost: 192.168.99.100
  elasticSearchPort: 9300
  elasticSearchCluster: elasticsearch
