spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres?currentSchema=fdkreference
    username: postgres
    password: password

  liquibase:
    url: jdbc:postgresql://postgres:5432/postgres
    user: postgres
    password: password
    change-log: classpath:liquibase/changelog/changelog-master.xml
logging:
  level.root: ERROR
  level.o.a: ERROR
  level.o.apache: ERROR
  level.no.brreg: ERROR
  level.no.difi: ERROR
  level.no.dcat: INFO
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/ld+json
    tomcat:
        compression: on
application:
  httpUsername: ${themesHttpUsername:user}
  httpPassword: ${themesHttpPassword:password}

management:
  endpoints.web.exposure.include: health, readiness

---

spring:
  profiles: develop,unit-integration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=fdkreference
    username: postgres
    password: password

  liquibase:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: password
    change-log: classpath:liquibase/changelog/changelog-master.xml
server:
  port: 8113


