logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: INFO
  level.org.springframework.web: INFO
  level.org.springframework.data.elasticsearch.core: ${LOG_LEVEL:INFO}
  level.org.opensaml: INFO
application:
  themesServiceUrl: http://reference-data:8080
  catalogUriPrefix: http://localhost:8099
  apikey: ${registrationApi_apikey:12345-ABCDE-67890-FGHIJ}
  altinnServiceUrl: ${registrationApi_altinnServiceUrl:http://registration-auth:8080}
  altinnServiceCode: ${registrationApi_altinnServiceCode:4814}
  altinnServiceEdition: ${registrationApi_altinnServiceEdition:3}
  clientSSLCertificateKeystoreLocation: ${registrationApi_clientSSLCertificateKeystoreLocation:conf/dummy-client-SSL-cert.p12}
  clientSSLCertificateKeystorePassword: ${registrationApi_clientSSLCertificateKeystorePassword:password}
  httpUsername: ${themesHttpUsername:user}
  httpPassword: ${themesHttpPassword:password}
  harvesterUsername: ${registrationApi_harvesterUsername:test_admin}
  harvesterPassword: ${registrationApi_harvesterPassword:password}
  harvesterUrl: http://harvester:8080
  openDataEnhet: ${FDK_ENHETSREGISTERET_URL:https://data.brreg.no/enhetsregisteret/api/enheter/}
  openDataEnhetProxy: ${FDK_ENHETSREGISTERET_PROXY_URL:http://nginx-enhetsregisteret-proxy:8080/enhetsregisteret/api/enheter/}
  apiRootUrl: http://nginx-search:8080/api
  # harvest every sixth hour
  harvestCron: 0 0 */6 * * *
  authentication:
    includedOrgforms: ADOS,FKF,FYLK,IKS,KF,KIRK,KOMM,ORGL,SF,STAT,SÆR
    includedOrgnr: 974760673,920210023,938275130


spring:
  jackson:
    default-property-inclusion: non_null
  hateoas:
    use-hal-as-default-json-media-type: false
  data:
    elasticsearch:
      clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch5:9300}
      clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}

security:
  oauth2:
    resource:
      id: fdk-registration-api
      jwk.key-set-uri: http://sso:8084/auth/realms/fdk/protocol/openid-connect/certs

server:
  tomcat:
    accesslog:
      enabled: true
    basedir: /tmp/fdk

---
spring:
  profiles: develop
  data:
    elasticsearch:
      clusterNodes: localhost:9300
      clusterName: elasticsearch
server:
  port: 8115
application:
  harvesterUrl: http://localhost:8082
  altinnServiceUrl: http://localhost:8077
  apiRootUrl: http://localhost:8080/api
  openDataEnhetProxy: http://localhost:8132/enhetsregisteret/api/enheter/ #mock

---
spring:
  profiles: unit-integration
  data:
    elasticsearch:
      clusterNodes: localhost:9399
      clusterName: elasticsearch
      properties:
        http:
          enabled: true
application:
  themesServiceUrl: http://localhost:8100
  clientSSLCertificateKeystoreLocation: ../../conf/dummy-client-SSL-cert.p12
  clientSSLCertificateKeystorePassword: password
  altinnServiceUrl: http://localhost:8077
  altinnServiceCode: 1234
  altinnServiceEdition: 42
  apiKey: 1234-abcde-56789-fghij
  harvesterUrl: http://localhost:8082

