
application:
  catalogUriPrefix: http://localhost:8099
  themesServiceUrl: http://localhost:8100
  apikey: ${registrationApi_apikey:12345-ABCDE-67890-FGHIJ}
  altinnServiceUrl: ${registrationApi_altinnServiceUrl:http://registration-auth:8080}
  altinnServiceCode: ${registrationApi_altinnServiceCode:4814}
  altinnServiceEdition: ${registrationApi_altinnServiceEdition:3}
  clientSSLCertificateKeystoreLocation: ${registrationApi_clientSSLCertificateKeystoreLocation:conf/dummy-client-SSL-cert.p12}
  clientSSLCertificateKeystorePassword: ${registrationApi_clientSSLCertificateKeystorePassword:password}
spring:
  hateoas:
    use-hal-as-default-json-media-type: false
  data:
    elasticsearch:
      clusterNodes: elasticsearch:9300
      clusterName: elasticsearch
saml:
  sso:
    metadata-generator:
      entity-id: difi.brreg.datakatalog.registrering.${registrationApi_OpenshiftEnvironment:dev}
    idp:
      metadata-location: file:conf/idporten/idporten-ver2.difi.no-v3_signed_meta.xml
      localMetadataLocation: file:conf/idporten/difi.brreg.datakatalog.registrering.${registrationApi_OpenshiftEnvironment:dev}.xml
    metadata-manager:
      refresh-check-interval: -1
    key-manager:
      public-key-pem-location: file:conf/idporten/difi.brreg.datakatalog.registrering.${registrationApi_OpenshiftEnvironment:dev}.xml
      store-location: file:conf/idporten/difi.brreg.datakatalog.registrering.${registrationApi_OpenshiftEnvironment:dev}.jks
      store-pass: ${registrationApi_ipStorePassword}
      default-key: difi.brreg.datakatalog.registrering.${registrationApi_OpenshiftEnvironment:dev}
      key-passwords:
        difi.brreg.datakatalog.registrering.st1: ${registrationApi_ipKeyPassword}
    context-provider:
      lb:
        context-path: /
        include-server-port-in-request-url: ${registrationApi_IncludeServerPortInRequestUrl:true}
        scheme: https
        server-name: ${registrationApi_ServerName:localhost}
        server-port: ${registrationApi_ServerPort:8099}

---
spring:
  profiles: prod
  data:
    elasticsearch:
      clusterNodes: elasticsearch:9300
      clusterName: fellesdatakatalog
logging:
  level.: ERROR
  level.no.brreg: DEBUG
  level.no.dcat: DEBUG
  level.org.springframework: INFO
  level.org.springframework.web: WARN
  level.org.opensaml: DEBUG
health:
  config:
    enabled: false
application:
management:
  port: 8181
server:
  tomcat:
    accesslog:
      enabled: true
    basedir: /tmp/fdk


---
spring:
  profiles: develop
  data:
    elasticsearch:
      clusterNodes: localhost:9300
server:
  port: 8099
  ssl:
    key-store: conf/idporten/ssldevelop.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: tomcat
application:
  altinnServiceUrl: http://localhost:8077



---
spring:
  profiles: unit-integration
  data:
    elasticsearch:
      clusterNodes: localhost:9300
      clusterName: elasticsearch
      properties:
        http:
          enabled: true
application:
  clientSSLCertificateKeystoreLocation: ../../conf/dummy-client-SSL-cert.p12
  clientSSLCertificateKeystorePassword: password
  altinnServiceUrl: http://localhost:8077
  altinnServiceCode: 1234
  altinnServiceEdition: 42
  apiKey: 1234-abcde-56789-fghij








