spring:
    profiles: docker
application:
  queryServiceURL: http://localhost:8081/search
---
spring:
    profiles: development
application:
  queryServiceURL: http://localhost:8091/search

  spring:
      profiles: test
  application:
    queryServiceURL: http://localhost:8071/search