spring:
  profiles: docker
application:
  retrieveDatasetServiceURL: http://localhost:8081/detail
  queryServiceURL: http://localhost:8081/search
---
spring:
  profiles: development
application:
  retrieveDatasetServiceURL: http://localhost:8091/detail
  queryServiceURL: http://localhost:8091/search
---
spring:
  profiles: test
application:
  retrieveDatasetServiceURL: http://localhost:8071/detail
  queryServiceURL: http://localhost:8071/search

