spring:
    profiles: docker
application:
  queryServiceURL: http://192.168.99.100:8083/search
---
spring:
    profiles: development
application:
  queryServiceURL: http://192.168.99.100:8083/search

  spring:
      profiles: test
  application:
    queryServiceURL: http://192.168.99.100:8083/search