spring:
  profiles: docker
application:
  queryService: http://localhost:8081
  queryServiceExternal: http://localhost:8081
---
spring:
  profiles: test
application:
  queryService: http://localhost:8071
  queryServiceExternal: http://localhost:8071
---
spring:
  profiles: develop
application:
  queryService: http://localhost:8083
  queryServiceExternal: http://localhost:8083
  fusekiService: http://fuseki:3030/fuseki
server:
  port: 8080
